import { Inter } from "next/font/google";  // Importing Inter font
import "../styles/globals.css";  // Global CSS file

// Setting up the Inter font
const inter = Inter({
  subsets: ["latin"],  // Using the latin subset for characters
  weight: ["400", "700"],  // Font weights
});

export const metadata = {
  title: "Nari Bazaar",  // App title
  description: "Generated by Nari Bazaar app",  // App description
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* You can add custom meta tags here */}
      </head>
      <body className={inter.className}> {/* Apply Inter font */}
        {children}
      </body>
    </html>
  );
}
