import { Inter } from "next/font/google";  // Importing Inter font
import "./globals.css";  // Your global CSS file

// Setting up the Inter font
const inter = Inter({
  subsets: ["latin"],  // Using the latin subset for characters
  weight: ["400", "700"],  // Defining available font weights
});

export const metadata = {
  title: "Nari Bazaar",  // App title
  description: "Generated by Nari Bazaar app",  // App description
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* You can add any custom meta tags here if needed */}
      </head>
      <body className={inter.className}> {/* Apply the Inter font globally */}
        {children} {/* Your page content will go here */}
      </body>
    </html>
  );
}
